language: node_js
node_js:
  - "0.10"

before_script:
  - npm install -g bower grunt-cli
  - gem install compass
  - bower install

script:
  - grunt test
  - cat ./coverage/coverage.lcov | ./node_modules/coveralls/bin/coveralls.js src/coffee/app

after_success:
  - git config --global user.email "mathieu.desve@me.com"
  - git config --global user.name "Mathieu Desvé"
  - grunt build
  - ./scripts/gh-pages.sh