language: node_js
node_js:
  - '0.10'
env:
  global:
    - secure: "hc0s49uOKKAlM/np6jCd4il3K0fI+gv/cQZTuu0f5xJEWxp9I4BuhDNjA/vzesA0192Z784pjjpuLkB63W7c7oEPuudhwxUbv80GCwdq2v2vI7i+tAdqLCGTlFl8VwsolSLI/g3DQTjxL54zuHxb9EIvlmkAu3togPtPSGS7DZA="
    - secure: "Lbi2depd+/VD/uc4vYmpEKcxgLftpFjLpoYLRuTlR25pXxjLVeTejqYoGBpdy32iTLG5+VthERZEm9zFtT67WaoUxE37+aoP1YYEUr5FHYCJsN5QPOnrwSUKE0ts7yH5z0HGeKCDy7O3VV3QhZ9jUt84iGk+w/WspD1pmcQZ9mk="

    - secure: "Mr5Hk9o4/3FDrPS6W7bpkt9DSGvKY3syTFFZZABMOGIKty1i7ELG65Po/fplQFvhFi4eewEUy0PzckevqHbIh8ZYAKa9DQjNw2Gz8fjvG1cFPbqPqALcW0kLEH/FBTGIWk0Gqsp/DunMf4mukYS52rqf7ED3g7qcZNbB8bUB7mw="
    - secure: "F3kKrUnlmoZ/BjIvX9YOiqouP3cfi4QGDkK5TxIMuoJ9crZpK8BDaayNGZyS6YoJgI9gUuaD5wE9l+ir7gbaSNm8X03WM9cS6LM7iLwYYBMbakx+XuoobMQOew/kXOZAxTfj2fUJIMs8Qxv8rQ8q1IKABk/OjXSXQ4uXBIZTaQM="
    - secure: "PNlNhimaNL+b2zW/NARpgZZfy91MShFk/PxK7EnScVMkhKFg1hNXdgxvbLP7jFt4ZKlP/PpUCkQFAEQ6p7bAlFO6BHg+jWS3Nj2niHLaMCRymn0I4ywxSjwGCvEQTBpe5jqxdhNJEXG7/5Xw8XpRnE7YSYatpmcZEITh6bY5Cak="
    - secure: "OWTu+nJ9tbTnrT3knKRySYfs7L5MUlp0B4tdIuWXzlZ0uqLmy2ylPHr56Nt/9EvH9QnY/cL2/2uNezd5d7Ii7jugwqejgjuSaFkbwaQxi3rbQGC1duyyfbhnQnajRJ8afyzMiFElxIzVCmP93+eiWdYlAIqlrQVPTEjwSpFJ1YM="
    - secure: "PYVGN9I+EEb7INgB8vfk31HK9vs7KUK4t7Les6dYn4E+3mh+jPNVZ0ZU3ZP1JJZBGhjOSvoCrl/C3/G4XIlPHJYIMDL+Rz623NGfEdekO/SnYtPu6Z/g3XFUASlF3jYTlVz9OHN1lMzBZ9QnudmkfhWcntPZ0REBMev93Ubm1Vg="
    - secure: "GB5Ilsb+vIBU9BHI6ecooHaWATYp8HaG8hckpf74dQBWh9W1gfn6TXTKROpq+uMexAFZV51qsOatzSU0R6RfEl+l+NRQEtS8zFDRJ814grx9G1HzuKiPYJklIDp7hvG0yczS0S0YnxIbcCcD5A7F5t8jXnt5kNWpDrw6lsNqsr0="
    - secure: "BjCItlrxmuGoS+WPkgKWK5Mx7WwFV74v8U/HbxilwBPM0nnwnjahHFlwHmk4PZzyk2osGkriJsoEV9nCbgczDZHrG7G99AYHgIcWfHhuujWYQ1L0EoZk0gmjU30JNWLd/0eue7P5Teyddh4jr9eEeKd0UyjdjhbKl7UsYb3ZQBM="
    - secure: "SILo9jttohP904KGwRps5zmM3lNjhiju467/SaHmEFrzNrD/+IUQcrRlHY1qArLaiZ5p+8EJbnI3SVPg/8cmY23pj3rm9wjvJOMQ5rYuyxS/IKAHDR8KBGZYM2ols/fU28NC+8FlQ/2tAiH4+Gu1wLS64aKXZaddpnkkuNrovcI="
    - secure: "AC8qsl1jSWGFzpYaOjAbjszySIReP9CyM25SeSyPi0/v56VR6sJFMo9gijLY5ZPPbhb8BjgaA+imTohGWW0Rshuv1NVPXPuPuD2giSIiWNS6iItBtubem0aTvhVen/bZyB3VPGL8G2nuBUZkNG0hWGq+MUADDndvuedrWtAwWwc="
    - secure: "AFuJ5oW7ny/wC/zIC7v9+aRenohlxH1ZesZUq90obZowqGrC8FS/m/B33UDrEQ1xNecmsNvr1yxWT6+pQjWN/8rhvJPPyPOBPIBceQRW+2a/zaqpOUCiI8WPRIfiAyrv7lxXCTcR2DZgPVBMvJm/BwpMgO5gS5jtXpXKJ9oeNDs="
    - secure: "XlBaCu7CYGwLulmsQKP0ngzCqsKrwDS7GPVLGNVjdEhG/1kXqbbAqUgpW19fYKi6+rRqZGMsXNd1/CkXSB9YaIg/tsgfPUg0sBjYKRYhhJ1ZLDT1ewipnuqbJlFOJEZeBuHUb5UH72iMgyWCmRDBiVhlKRWxAaTGdcm2J4myXKI="
    - secure: "e+gQtJrsxUxEBK2jW1Z+MKrLlccU/EVHW2mmXcLd23GDjnVREkPCcsj/zZpUiqeEiAQIu3qWol2gSZHfUntEhNjGXe8Uoqjpb5ApZNWWHJknaE+j0SG9JRn8e7Ch0XisVwvIrXoGOqXt27Be5hR0BnmqS6ktthTNZw0ZGSJAZn0="
    - secure: "fapYx+8qI8rKOt05FCHoWQ/57xthi0Q56iEf6XabSOU0sJObh7cjhYh9tvqAUpO4V2xDCN5mJcB4EP7PSDQ+uPLRvd6RbbesGveX2lgOJ+oIY+N/M2pqnuAmXwkE8BLmm9Cq5++V4NSbLqgL8j1GXgzqFlWdW1aMUYqrBUrdj8U="
    - secure: "RTZnOGEVz4HP90d3dXrBZ7+u/UK/1H3CKQ1MyskH35OIkeK4SKjY3JTlqr4ruMaLzcGkiPPIoAyL7/pO/wQ03DNAkaLRrl4BTqWnVCgivGpxtSH6PX+jgt6QyEb5BgJ9zInLNESPRMhtXRsgcKc6pEP3Hixm3N8xerfLBeM8U3E="
    - secure: "F71xdB821SMfgkGAZGAlGw2gd54obTVWNyh3Ifuxa8Ne0SpszhQZhYDzgSmTbo3wbZPkshcJKBm4Onhvsemf/z60YTSxUdyiP31+Ixz/d6GWIsWgKzNtwHxDFuSom7T5+TVOaEzul1VaN9Ywpyuj2OM60SHQWmq0b3JmQnDBWes="
    - secure: "STA3wj2WKmnDkvqcpDb73by/Cwqz/1Nsp19r6p5+1qMkwe1sasf3GXPUP6FoLl5fDQJrdF5HCJOv40KC7au+XQ36ZLonus4cTHx48Q4spJKX0sC50qvUaOTC9+oiU9pIIxDEnrh01Nq57AV/0nGbdrZlnopNfPSiZfBcDdMFJUM="
    - secure: "ZbSFArUPRXyxdgdix4Apxxg0Z0khLN/zbnZlqz08mkGVAUzHVh0MFlq6lXaGDPL/rk0g64OO1yUkpexGdPiNXJFGj7k23IdXK840T1+XoRQKrHFdSiisNHicXWEmH8FkYoVRJGL7NAcVrBiyyZOJ2PRYB2D2VbeOSJ/2oUYL5Gk="
    - secure: "fBONuwxSqZs89TYZHdkYnHQelNxnexLW+zzvOsr5dPr00SoBPYKAbdM8ZJV2wnhIXlEKMKceffiksm4CDLUumtmjki2+RNUTuwZYSmUtw5gUCRjtiLO/N+WJ2ZNHbo46bWKlftsgS/oZ+ax3D3IuG6ruEwwAN5aMM17W9l7CrPw="
    - secure: "chzc8pAFk9QSx+bUdvkYLdf5+JzLLw6kqSAAxuakYqd/xOS/svbXd/oxzCJOn4HBX+bFRtziMQj6VC6irtUHGQEBCXnnD3Hcu5Kt99KTHRyORvwX/C2R5q+o1bPYdWXb/14wtRUJFmHU5xhEH16Q68/exWyFsSyuWIl7MnXrrJc="
    - secure: "YOUh2JQKsr6XxTlkNyIvxUZRcQt4HOC7xyiUEaSCfii54KWyGhqtcIRhz+EpD0l5taj/e2vEYDt8k8jKf3lJTVdx8wt6XvRCt9UtxTa8c5ZyBRI+Uev3tcGtjREDsjJlGx/R2VVUrcGW6V/HdwGJ82x+bfoo9ninTod3igyS4hU="
    - secure: "G6Oj2L5yHLSxGZ7GmOHa2s8Z7ChUGJgUFRPtEiw+vK8sysRRN2enMCvnaC75rOSifpK8ej51uy0eUA+eazD92WkvEgYwzfbjFSOjYthy3SIetirXyHAwe8sc0dy4+UotQwX5xOZTVl+JjndvQHOaJgiYtn+fz61GPaxNc1++bVw="
    - secure: "W2cDJ6ACKQQSALnzr1qj6sDHMAY84kMuuE7eAFH7bTHqsXzsj2lEEwDRcN3AmgFYuGe9pCPnzDb1xeCJ7qVBQd96ucaOiDMErr4B4oGirAsYqFCOYUz/LP00F/21/IgRYlKzU/dBdGdRSwczwGWX+vnXU3qNtwYb6GwblDJ7PKs="
    - secure: "Hb55+EgFFGw8h+EeoyfuOjBsldmly/i7sEO800zGmqTOStyhCBtVj/XGBG7Ag+v3loJ8r50n1Hj+tuUW01RJHQ2LJoiTBrLSpY8co+F87rMs1MASoC2qhbKHDupEHUOyd3nmhrdyHCrhSl4/QVWDSpzt4XEGE0bjrwuJGsYRCi8="

install:
  - npm install -g bower grunt-cli
  - gem install compass
  - npm install
  - bower install

script:
  - grunt test

after_success:
  - cat ./coverage/coverage.lcov | ./node_modules/coveralls/bin/coveralls.js src/coffee/app
  - grunt build
  - BRANCH=master REPO="https://$GH_USER:$GH_PASSWORD@github.com/mazerte/test-footguard" ./scripts/gh-pages.sh
  - BRANCH=master APP=test-footguard ./scripts/heroku.sh
