language: node_js
node_js:
  - '0.10'
env:
  global:
    - secure: "hc0s49uOKKAlM/np6jCd4il3K0fI+gv/cQZTuu0f5xJEWxp9I4BuhDNjA/vzesA0192Z784pjjpuLkB63W7c7oEPuudhwxUbv80GCwdq2v2vI7i+tAdqLCGTlFl8VwsolSLI/g3DQTjxL54zuHxb9EIvlmkAu3togPtPSGS7DZA="
    - secure: "Lbi2depd+/VD/uc4vYmpEKcxgLftpFjLpoYLRuTlR25pXxjLVeTejqYoGBpdy32iTLG5+VthERZEm9zFtT67WaoUxE37+aoP1YYEUr5FHYCJsN5QPOnrwSUKE0ts7yH5z0HGeKCDy7O3VV3QhZ9jUt84iGk+w/WspD1pmcQZ9mk="
    - secure: "JbRb25VpT64Ku+eq450LkfzEyA7r5KNueUynMciDsYfNDgGTySSnxyF1Z3A4lyEnQPwG5ZIKORBJwXXnIsziX+gzIa1YUeJhgn8Fa1AA6J3txhc0GyVU10fGPr6RtetSuPfDrBwdL0u9g1LxAPh5QmwXkJ1/tcw6+BnPo6c23VA="
    - secure: "grc6SrcbDECEDCd+UKWQTYpH5PIyO+OeQgF/3WjF5DIO6QYb6RIJ5rqyaeiszAiswcZxwD6L+2oaT0MbDd0Bvs4wjepZFxvcWwpBtrlxy7XQDCKxNNr4/xW2rUhNVkIlaMTdDHLo6I07VjzBmYSgbHvx0b9LrUZwerfCD9wEzDs="
    - secure: "OZnxPYDVdMxMGJysqUlSVXnncjOL9nPhgrj0DcCwC0OqP0rHU14raAJKNfykp8tCUGogu8uC8e8i7GFcFAkAWHsu2KG52DfptLEe1DJBJkKUwZtTiNJJQ3M/fNsm3wvQvHNkM2ZoKs4IRVWRSvKlQVkPtDH/80LgTew7XLFpt1c="
    - secure: "G0TBRVsMrw8EqUF2itRDnYpBPaDuTOnlYKQmY82VZ/6uChn1SvdScFQWRWnKIvO5YHtJ8iFhWYW2obOHGIc1Bcfv0YeJzbRWzGskul/5TPvXN3sXv6wnKisCY6Nt1VGGaLobEUzWTVpVydYrUylK6qpxiFjac6ihKY1LaTaAO9M="
    - secure: "RH2jXbX6G0tD4gCA25sHEyI7P3tgG0QVfF7P0dlaRE0unIGKSLjvqcT7PRTN4hoH33BzifdwR3jxpCgpSuDDOWA15vWm6hEETsh4QbdtyEIn227vTlTSA7kt8spvbUsMvtMuZKwCI1cAyjNkgwLqQdUvcLWTMQ+OGIBUt101qZ0="
    - secure: "ilQWZxC2dzKFt9y6CqRhgdXfOWcs6WAczyPECff7efiavQphNQr6ypc0xFtMZCcurtaZfLLo8aCT+M561q068Yzd4Qxu1XTanOrMFVCC1ON7XyGVir1cRe7EXLTjQXmKrbEofiCT8PuFqLNwrFcmzUPxC7vX6TA62c7HLHB/teo="
    - secure: "IWrL0RW82JFzyfDpZ/kUUSlVCigFG//hbbN2AB6UUNnAiJjR8Fss7K4u0CDYM3MYgoPdD9+YhR7NBxdP7yde3x6yk6KSMVRRVMfugqcY2erauHXVmXlUprQlt5YB7tBAvfUuxgngbx9aI2QHSbnN47Ih1XMGLQMTWivxjPv/O+s="
    - secure: "V9DkDx5Ig/aQTsj7JlaXbtwHjjvGZMMz5X3TFxz/bZKJZK5eUJQHIvGCUqyfLkEMA4cvbB+U9kYeDjRXKRrGFcc/zGuSyaQ5i5ocNosxLd4NzeDV5Dfvk+hBGH8NhhfLn1kKCW/sQHJp00kA7bRPVfSXQkMeuoMJAWi4x9PKKgA="
    - secure: "ceIxAnzq5Tg3vkCnpzbKskXA0ZIYF4nIL5aMcLzGuqlEkufRmbbxNFvO85d1opmkfg7qW4mmOD8xunzVqG9pa0gigCm45S2wQ/YctYP6etHgkE9KrtcJncUlk6ToayJK2ETrSrZtjjvSfnTqgsMES8chxIoNH278zEFjHMyDt30="
    - secure: "XoqooA/zOBXQMaRPo5/CDynaaTDUoF/5u5Y52+4+PcpHB2dQqiDY+K/w57nE+GTn+2yqw/CjTpbGS/khq5Ihmppl8E8/pLtln6Pllsr7CSr7tXcNuqLneoYpK2MhYlcJyKYGqCGyxJANTSFQ6MRQtmxbpp0gLIMAMQEDn8UGDpY="
    - secure: "AzlaZAmcR6hgHCyOwIV7OJeiRIbVrb2DyEK9x9unHf5Snt9xosc7GRTJAYlgv0MHHZARtTHLT++YpnKZW9k5nTtC8WzAt60pAG0J6lAtTndbkFiNJZYoR4CpBruqnaYArBOY3Kjk6Vh/2La0OUZW8fIlpvvoWT3snhLOhmuqWso="
    - secure: "ZY74N0Rcq8P97T245pUVhhZO/cDfEgGSZ82N0Z9nMuFvZYlQ3p4cEimhPeq4+o/nl6aFEUIy/z9zkp+T4I5+CDF92IZachFgqZVyppZ67swejBXg/BGo01Ar3EYKVUY7o9EVYhr2/ikmwn+IvuZcVruis5RXd3YlFxOf5dM2V0c="
    - secure: "MVdfnA26QkcvlYtLuW588bsmL0qsKEct4CKqRoZUwXU0+DUdY0Sc+lEbFomym4CSd80BkhfPfmqT+mwmHJNqRCKNR1vyBmZX2TiUbW6t7icyFAK9Yzg5bWoxCFw3LvC1FICo/eRMtBTiDHGpPvFdt+KI7jZra4d/v19GygM+CgY="
    - secure: "aQXHEYKBBstBbpusfWC3PmHOe5byPjy6rNpw+4BxMOIEVXWOFRipx6wuDh1aa3WIvtFDzWxOQVse7EJBtJdVu/tnzy4v0P4tbEkhMd3nFG+yGZm7bUHU4TjN0vig/VgtmCRery4r9pcAhlx2nw9elEcHoacZ4P9p3nOMRn4YFNg="
    - secure: "aX2sOTm/UdtemXQQ7NOewSM5scZ/qpo5eO3v3DsH93mpHn8tQryFZrfYzmBbNOz7i7FHdraVeHu/HcBMCYKsRwVuezL/EDtFvfOjtoKiepWDSEhWxmKOItnVjy8hdwFTYD4QvO5s6RMfVatJAvNpkJu9ll0hgPIok0JohQAak/g="
    - secure: "cX3ZIjA9UxtyD7EXDOKnjpUVGXNV6pr6BZNk4k6L7tuf/ugkiha1uFBta9eVhTpZ/AUsXoiOG8HVzyUxE6P5YWxT1FzRmVNEqvIn1VwVA+D1OayXjHBBmhlfVhXsQ6f+8RfzoGWGNgNg/rs8+T9Q6wc2mM/DbO5vnSNbRY8KbP0="
    - secure: "g979NPeATaRTh3vPrWY5ByhXxwbOZl4I2crSiPXlU02h4V671CJV8F/utkm8/jUfW0ooMNHkZkCKytgu8Np1Z/BcOuxEqSS3xA2unfcT6iLgI9J/0wxKbFWyxy9YGzkmCPfzqUBQtffK+d38Z1r/NJbXeTXEI7tnHrIajOC1ObU="
    - secure: "B2F4hblW5MDRLUzdljCbevzHONnK/hlS/Vn5SNW6Pa+cl1qlYhmOcAylxDtT838T+DeE41A0PFMgwtmpmKEbJilRvP3Pmlqt6nJyN4+A0BufAYWWQUcoh7uUQT/KTT0v414TXI4TZnb219bFvmoDyfWXTmEqy0O6wTtYxtzYHPY="
    - secure: "F5fcGScwZfsYU8sTCrlO0VzTLeGOsAKLRZwldvhyqzdrjwRXa8RsB8oc1nlX8Yg5q6x0UCWz1pul8FYgtMZv5HyBSYBn8q4+2YFzJTPUEEr+pg0+jzhlQ0UsP6qj0Ya4Um+XEs1WKUWdAPDFYDpcYwNXIJMCQBkjr08vQrgxoSA="
    - secure: "eGQuM2da1r1c+1hTupIwyTTlt2WcGV8eppUZTWzJeg6u7Y78WqtDI1fTflZOS98HXX5mv7Q0kB8074aru8PzTA5LCGzCa3ph1O/CXBpsAdF6HoHOfWEfRCxwe/HdL+2zNMDc0vyz708BniUd9lHsSuzHAPBwWmyj3YNk59gv1IA="
    - secure: "I7n4iJry/Rsm6xRkIXsaCI5FVwsrTshxHbiy6q1qzXMxlrCcn1shp7tNhjsgOIt23IE9syuGwdqvia7skcWLPZm1wDJG1La8tzsgk1Mked33sWCU454NQt8PWd3sJtNd6Nv/eTIISaWj//OxrHeIwIvYVaGDUm7sFxW8/QjbGUs="
    - secure: "Mw866/IU5vxX05vM/AtsKNfL+624beRtptV+5fY6OAPcEKsnSoR59YzMHxzHXdymImEKbssOZRVHPQdgpJ91LHicoJYPsHhaA60twbatTzUoSgscWvWm12NGVH5oBVp5QpjwLPR99iRDGelDNwtVyY7+yKzwRQHETQIfv/vqglw="
    - secure: "RvBvVevIBMR+K3ZdnIFN9vF2OABUQwD5NKiFuI7gVOJpvjxjShrKTMd/T9nEMQFa5RLLAVW0HoOocmjqkC8/NwVIT9/nbeuBH7hp+31A7Vn69gvGYNMHiRzueSWW6Wf7LHoYS3UvTEZzStd4jLOyPh5o7/4KlKeCvviA7fgobTc="
    - secure: "EVvj3eRVdSmNyRo3nzPDNS2cCe5O+33dgYPnDW5Jv5jrb5heSRnw/fiLwEUyjCceE5pIaRAj6QagjeR/+TXL+G4I9+5RmaVy23sVU0+wKkHp8HnPHMKTlWqX7FmPpJd1e64/wu8FOm1FR9dD76nPa5WXs7N1gWMTli88UDlbNYk="

before_script:
  - npm install -g bower grunt-cli
  - gem install compass
  - bower install

script:
  - grunt test
  - cat ./coverage/coverage.lcov | ./node_modules/coveralls/bin/coveralls.js src/coffee/app

after_success:
  - grunt build
  - REPO="https://$GH_USER:$GH_PASSWORD@github.com/mazerte/test-footguard" ./scripts/gh-pages.sh
  - APP=test-footguard ./scripts/heroku.sh
