language: node_js
node_js:
  - "0.10"

env:
  global:
    secure: hc0s49uOKKAlM/np6jCd4il3K0fI+gv/cQZTuu0f5xJEWxp9I4BuhDNjA/vzesA0192Z784pjjpuLkB63W7c7oEPuudhwxUbv80GCwdq2v2vI7i+tAdqLCGTlFl8VwsolSLI/g3DQTjxL54zuHxb9EIvlmkAu3togPtPSGS7DZA=

before_script:
  - yes | git config --global user.email "mathieu.desve@me.com"
  - yes | git config --global user.name "Mathieu Desvé"
  - npm install -g bower grunt-cli
  - gem install compass
  - bower install

script:
  - grunt test
  - cat ./coverage/coverage.lcov | ./node_modules/coveralls/bin/coveralls.js src/coffee/app

after_success:
  - grunt build
  - REPO="https://$GH_USER:$GH_PASSWORD@github.com/mazerte/test-footguard" ./scripts/gh-pages.sh