language: node_js
node_js:
  - "0.10"

env:
  global:
    secure: RKmtDqHqK1CokgNUTT4piRN+Fz0guBzgisHtncwyPv4V81jfPzohB5y/pPZ6cmC+znc8w2qGMJoUrptiiFhb5LvtCji/iWLinAiOBfhHYqUExPk8yz9qfW1+jTUQ5i8wn/YNiR1Thysop3GpNG9jk+n2CqLEs5pKrp4DrfRk47Y=

before_script:
  - npm install -g bower grunt-cli
  - gem install compass
  - bower install

script:
  - grunt test
  - cat ./coverage/coverage.lcov | ./node_modules/coveralls/bin/coveralls.js src/coffee/app

after_success:
  - grunt build
  - REPO="https://$GH_USER:$GH_PASSWORD@github.com/mazerte/test-footguard" ./scripts/gh-pages.sh